### ISSUE TITLE
Duplicate functionality

### ISSUE THREAD

**Issue by johnkeates** [saltstack-formulas/beats-formula#1]
We already have https://github.com/saltstack-formulas/filebeat-formula. I'm not sure if having a 'beats' formula with multiple responsibilities is the best idea.

**Comment by psmiraglia** [comment]
All the Beats modules share the same installation and configuration process, so I grouped them in a single formula. According to my experience, when you use Filebeat you will probbably need also Metricbeat to collect metrics about your environment. So, why not having them a single formula?

Anyway, I'm the author of the formula, so I don't think I'm the right person to state about its usefulness and goodness. Let's wait for comments from others... 😄

**Comment by whiteinge** [comment]
@psmiraglia I apologize! I did not see that we had formula repos for both already. (Seems the GH repo search doesn't handle partial-name searches -- e.g., "beat".)

I agree with OP, it's probably best to keep them separate. How do you feel about moving any missing functionality from this repo into those? Then we could either retire this repo, or if they're often used together perhaps this repo would be a good "glue" that uses `import` and `extend` to reference files from the other repos to coordinate installing both as one.

https://github.com/saltstack-formulas/filebeat-formula
https://github.com/saltstack-formulas/metricbeat-formula

**Comment by psmiraglia** [comment]
So, basically I re-invented the wheel. Good to know... 😒

No problems from my side about moving missing features in filebeat/metricbeat specific formulas. About the "glue" formula, I don't know... I'll think about that during the week-end...

**Comment by psmiraglia** [comment]
I took a look in Filebeat/Metricbeat formulas and IMO, there some aspects that could be enhanced. In particular, the MB formula could include the YUM repository management while the FB formula (as @johnkeates already highlighted in [filebeat-formula/issue-9](https://github.com/saltstack-formulas/filebeat-formula/issues/9)) requires a massive re-design.

About the "glue" formula, I think it should require a coordination among the authors of the specific formulas (e.g. to avoid conflicts amond state IDs). I don't know if that's worth the effort.

**Comment by johnkeates** [comment]
I agree that the glue formula needs some more thought. I've been looking into that sort of stuff but I haven't come up with a solution yet. Good inter-formula dependency management requires some sort of package manager (like SPM that never got off the ground), and every time I poke the salt ticket for that a lot of things are said but nothing gets done.
